### ISSUE TITLE
use github desktop with wsl

### ISSUE THREAD

**Issue by alok-old** [Vets-Who-Code/windows-dev-guide#18]
Is there a way to make github desktop work with wsl. IO operations are slow in github desktop when adding any project from wsl

**Comment by usmcamgrimm** [comment]
GitHub desktop isn't built to run in WSL. You have to run it in windows and manage repos you have in WSL. Why not just install the GitHub CLI?

**Comment by alok-old** [comment]
@usmcamgrimm It's just that GitHub desktop makes few things easier like when having conflicts and adding selective changes in a file

**Comment by usmcamgrimm** [comment]
@alok-debnath Unfortunately since it's not built to run inside WSL you're going to deal with the slow operations.
