### ISSUE TITLE
Add Python Section

### ISSUE THREAD

**Issue by jeromehardaway** [Vets-Who-Code/windows-dev-guide#3]

**Comment by Takomane** [comment]
For these issues, you are seeking someone to add to the section with images, a description of the section, and how to install correct? I have python installed and use flask for my personal app, so I feel confident in being able to draft a how to section if I could be assigned to this issue.

**Comment by stephanlamoureux** [comment]
> For these issues, you are seeking someone to add to the section with images, a description of the section, and how to install correct? I have python installed and use flask for my personal app, so I feel confident in being able to draft a how to section if I could be assigned to this issue.

Hey Nick, That’s correct. It wouldn’t have to be too in depth, but I would like it to cover installing on WSL, pip basics, Django, and Flask. With any windows terminal screenshots as needed.

Any must have Python related vs code or chrome extensions could also be added to their respective sections.

**Comment by Takomane** [comment]
> > For these issues, you are seeking someone to add to the section with images, a description of the section, and how to install correct? I have python installed and use flask for my personal app, so I feel confident in being able to draft a how to section if I could be assigned to this issue.
> 
> Hey Nick, That’s correct. It wouldn’t have to be too in depth, but I would like it to cover installing on WSL, pip basics, Django, and Flask. With any windows terminal screenshots as needed.
> 
> Any must have Python related vs code or chrome extensions could also be added to their respective sections.

Understood! Thank you! I will get started on it.

**Comment by stephanlamoureux** [comment]
I updated the guide with the new sections and the TOC, which should help with merge conflicts.

I also did some squishing so you may have to reset the branch or clone again.
