### ISSUE TITLE
Add Ruby Section

### ISSUE THREAD

**Issue by jeromehardaway** [Vets-Who-Code/windows-dev-guide#5]
Ruby, Rails, IRB, RubyGems etc. 

Windows Terminal screenshots, and must have vs code plugins/chrome extensions.

References and footnotes added as needed.

**Comment by usmcamgrimm** [comment]
I can take this one.

**Comment by stephanlamoureux** [comment]
I updated the guide with the new sections and the TOC, which should help with merge conflicts.

I also did some squishing so you may have to reset the branch or clone again.
